# Generated by Django 5.1.15 on 2026-09-29 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "shift",
                    models.CharField(
                        choices=[("AM", "Mañana"), ("PM", "Tarde")],
                        max_length=2,
                        verbose_name="turno",
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="litros"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestock.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "ordeño",
                "verbose_name_plural": "ordeños",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["farm", "updated_at"],
                        name="production__farm_id_33aec8_idx",
                    ),
                    models.Index(
                        fields=["animal", "date"], name="production__animal__354e34_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("animal", "date", "shift"),
                        name="uniq_milking_animal_date_shift",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Weighing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="peso (kg)"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestock.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "pesaje",
                "verbose_name_plural": "pesajes",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["farm", "updated_at"],
                        name="production__farm_id_f97cba_idx",
                    ),
                    models.Index(
                        fields=["animal", "date"], name="production__animal__0b0d82_idx"
                    ),
                ],
            },
        ),
    ]
