# Generated by Django 5.1.15 on 2026-09-29 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="identificación"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "propietario",
                "verbose_name_plural": "propietarios",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="código")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brands",
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
                (
                    "title_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brands",
                        to="livestock.owner",
                        verbose_name="titular propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "fierro",
                "verbose_name_plural": "fierros",
            },
        ),
        migrations.CreateModel(
            name="Paddock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paddocks",
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "potrero",
                "verbose_name_plural": "potreros",
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="arete"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="nombre"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Macho"), ("H", "Hembra")],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("calf", "Ternero/a"),
                            ("heifer", "Novillo/a"),
                            ("cow_lactating", "Vaca en ordeño"),
                            ("cow_dry", "Vaca seca"),
                            ("bull", "Toro reproductor"),
                        ],
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("sold", "Vendido"),
                            ("dead", "Muerto"),
                            ("culled", "Descarte"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"sex": "M"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_as_father",
                        to="livestock.animal",
                        verbose_name="padre",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"sex": "H"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_as_mother",
                        to="livestock.animal",
                        verbose_name="madre",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="livestock.brand",
                        verbose_name="fierro",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="livestock.owner",
                        verbose_name="propietario",
                    ),
                ),
                (
                    "paddock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="livestock.paddock",
                        verbose_name="potrero",
                    ),
                ),
            ],
            options={
                "verbose_name": "animal",
                "verbose_name_plural": "animales",
            },
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(
                fields=["farm", "updated_at"], name="livestock_o_farm_id_193e2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["farm", "updated_at"], name="livestock_b_farm_id_25c5fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("farm", "code"), name="uniq_brand_farm_code"
            ),
        ),
        migrations.AddIndex(
            model_name="paddock",
            index=models.Index(
                fields=["farm", "updated_at"], name="livestock_p_farm_id_b3aa7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paddock",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="uniq_paddock_farm_name"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["farm", "updated_at"], name="livestock_a_farm_id_05fdfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["farm", "status"], name="livestock_a_farm_id_8a83a4_idx"
            ),
        ),
    ]
