# Generated by Django 5.1.15 on 2026-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="status_changed_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de cambio de estado"
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="status_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="motivo del cambio de estado"
            ),
        ),
    ]
