# Generated by Django 5.1.15 on 2026-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0002_animal_status_changed_at_animal_status_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="foto"),
        ),
    ]
