# Generated by Django 5.1.15 on 2026-09-29 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vaccine", "Vacunación"),
                            ("deworming", "Desparasitación"),
                            ("antibiotic", "Antibiótico"),
                            ("vitamin", "Vitamina"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("product", models.CharField(max_length=150, verbose_name="producto")),
                (
                    "dose",
                    models.CharField(blank=True, max_length=100, verbose_name="dosis"),
                ),
                (
                    "withdrawal_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="días de retiro"
                    ),
                ),
                (
                    "withdrawal_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de retiro"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestock.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento sanitario",
                "verbose_name_plural": "eventos sanitarios",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["farm", "updated_at"],
                        name="health_heal_farm_id_1dcc46_idx",
                    ),
                    models.Index(
                        fields=["animal", "date"], name="health_heal_animal__8e8e67_idx"
                    ),
                ],
            },
        ),
    ]
