# Generated by Django 5.1.15 on 2026-09-29 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ubicación"
                    ),
                ),
            ],
            options={
                "verbose_name": "finca",
                "verbose_name_plural": "fincas",
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="core_farm_updated_659f7d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FarmMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("technician", "Técnico"),
                            ("operator", "Operador de corral"),
                        ],
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía de finca",
                "verbose_name_plural": "membresías de finca",
                "indexes": [
                    models.Index(
                        fields=["farm", "updated_at"],
                        name="core_farmme_farm_id_efaa81_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "farm"), name="uniq_membership_user_farm"
                    )
                ],
            },
        ),
    ]
