# Generated by Django 5.1.15 on 2026-09-29 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReproductiveEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("heat", "Celo detectado"),
                            ("service", "Servicio (monta/IA)"),
                            ("palpation", "Diagnóstico de preñez"),
                            ("calving", "Parto"),
                            ("drying_off", "Secado"),
                            ("abortion", "Aborto"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "service_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("natural", "Monta natural"),
                            ("ai", "Inseminación artificial"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="método de servicio",
                    ),
                ),
                (
                    "bull_straw",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="toro/pajilla"
                    ),
                ),
                (
                    "palpation_result",
                    models.CharField(
                        blank=True,
                        choices=[("pregnant", "Preñada"), ("empty", "Vacía")],
                        max_length=10,
                        null=True,
                        verbose_name="resultado de palpación",
                    ),
                ),
                (
                    "estimated_calving_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha estimada de parto"
                    ),
                ),
                (
                    "suggested_drying_off_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha sugerida de secado"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestock.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farm",
                        verbose_name="finca",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento reproductivo",
                "verbose_name_plural": "eventos reproductivos",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["farm", "updated_at"],
                        name="reproductio_farm_id_d4edc3_idx",
                    ),
                    models.Index(
                        fields=["animal", "date"], name="reproductio_animal__19bf7b_idx"
                    ),
                ],
            },
        ),
    ]
